#!/usr/bin/env bash

while read -r line; do
    version=$(basename "${line%/vmlinuz}")
    echo ":: Running kernel-install for kernel $version"
    
    kernel-install $1 "${version}" "${line}"
done

# first check if we are running in a chroot
if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
    echo 'Running in a chroot, skipping cmdline generation'
    exit 0
fi

# If needed, set /etc/kernel/cmdline to enable kernel-install in a chroot
if [[ ! -e /etc/kernel/cmdline ]]; then
    mkdir -p /etc/kernel
    
    BOOT_OPTIONS=""
    read -r -d '' -a line < /proc/cmdline
    for i in "${line[@]}"; do
        [[ "${i#initrd=*}" != "$i" ]] && continue
        [[ "${i#BOOT_IMAGE=*}" != "$i" ]] && continue
        BOOT_OPTIONS+="$i "
    done
    echo ${BOOT_OPTIONS} > /etc/kernel/cmdline
fi
